"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { KeyRound, ShieldCheck, Check, AlertCircle } from "lucide-react";
export default function ChangePassword() {
  const router=useRouter(); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);if(form.get("newPassword")!==form.get("confirm")){setLoading(false);return setError("Les nouveaux mots de passe ne correspondent pas.");}const r=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")})});const d=await r.json();setLoading(false);if(!r.ok)return setError(d.error);router.replace("/tableau-de-bord");router.refresh();}
  return <main className="password-page"><form className="password-card" onSubmit={submit}><div className="login-icon"><KeyRound size={23}/></div><span className="eyebrow">SÉCURISATION DU COMPTE</span><h1>Créez votre mot de passe</h1><p>Vous utilisez un accès temporaire. Choisissez un mot de passe personnel avant de continuer.</p>{error&&<div className="form-alert"><AlertCircle size={16}/>{error}</div>}<div className="field"><label>Mot de passe temporaire</label><input className="input" name="currentPassword" type="password" required/></div><div className="field"><label>Nouveau mot de passe</label><input className="input" name="newPassword" type="password" required minLength={12}/></div><div className="field"><label>Confirmer le nouveau mot de passe</label><input className="input" name="confirm" type="password" required minLength={12}/></div><div className="password-rules"><span><Check size={13}/> 12 caractères minimum</span><span><Check size={13}/> Majuscule et minuscule</span><span><Check size={13}/> Chiffre et caractère spécial</span></div><button className="btn btn-primary" disabled={loading}>{loading?"Enregistrement…":"Sécuriser mon compte"}</button><small className="safe-note"><ShieldCheck size={13}/> Votre mot de passe est stocké sous forme chiffrée.</small></form></main>;
}
