"use client";
import { FormEvent, useRef, useState } from "react";
import { Sparkles, Send, Scale, TrendingUp, Percent, FileBarChart, User, AlertCircle, ShieldCheck, Database } from "lucide-react";
type Message={role:"user"|"assistant";text:string;records?:number};
const suggestions=[{icon:Scale,text:"Compare les offres entre les deux grossistes les plus actifs."},{icon:TrendingUp,text:"Quels produits sont le plus souvent en promotion ?"},{icon:Percent,text:"Quelles sont les meilleures remises de ce mois ?"},{icon:FileBarChart,text:"Génère un résumé exécutif de la veille concurrentielle."}];
export default function AssistantPage(){
 const[messages,setMessages]=useState<Message[]>([]);const[question,setQuestion]=useState("");const[loading,setLoading]=useState(false);const input=useRef<HTMLTextAreaElement>(null);
 async function ask(text:string){if(!text.trim()||loading)return;const q=text.trim();setMessages(m=>[...m,{role:"user",text:q}]);setQuestion("");setLoading(true);const r=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q})});const d=await r.json();setMessages(m=>[...m,{role:"assistant",text:r.ok?d.answer:(d.error||"Une erreur est survenue."),records:d.recordsUsed}]);setLoading(false);setTimeout(()=>input.current?.focus(),50)}
 function submit(e:FormEvent){e.preventDefault();ask(question)}
 return <><div className="page-head"><div><h2>Assistant d’analyse IA</h2><p>Interrogez vos données autorisées en langage naturel et obtenez des comparaisons fiables.</p></div><span className="ai-status"><i/> IA opérationnelle</span></div>
 <section className="assistant-shell card"><header className="assistant-head"><div className="assistant-avatar"><Sparkles size={22}/></div><div><h3>PharmIntel AI</h3><p>Analyste de veille concurrentielle</p></div><div className="assistant-security"><ShieldCheck size={14}/> Réponses limitées à vos données</div></header>
 <div className="chat-area">{messages.length===0?<div className="assistant-welcome"><div className="welcome-orbit"><span><Sparkles size={28}/></span></div><h3>Que souhaitez-vous analyser ?</h3><p>Je peux comparer des grossistes ou des laboratoires, repérer les tendances et générer une synthèse à partir des documents de votre espace.</p><div className="suggestion-grid">{suggestions.map(({icon:Icon,text})=><button key={text} onClick={()=>ask(text)}><Icon size={17}/><span>{text}</span><Send size={12}/></button>)}</div><small className="data-note"><Database size={13}/> L’assistant utilise uniquement les données auxquelles votre rôle donne accès.</small></div>:<div className="message-list">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div className="message-avatar">{m.role==="assistant"?<Sparkles size={16}/>:<User size={16}/>}</div><div className="message-bubble"><span className="message-name">{m.role==="assistant"?"PharmIntel AI":"Vous"}</span><div className="message-text">{m.text}</div>{m.records!==undefined&&<small>Analyse fondée sur {m.records} enregistrements récents</small>}</div></div>)}{loading&&<div className="message assistant"><div className="message-avatar"><Sparkles size={16}/></div><div className="message-bubble"><span className="message-name">PharmIntel AI</span><div className="thinking"><i/><i/><i/> Analyse de vos données…</div></div></div>}</div>}</div>
 <form className="chat-input" onSubmit={submit}><textarea ref={input} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask(question)}}} placeholder="Ex. Compare les promotions de Biopharm et Saidal…" maxLength={1000}/><button disabled={!question.trim()||loading} aria-label="Envoyer"><Send size={18}/></button><small>Entrée pour envoyer • Maj + Entrée pour une nouvelle ligne</small></form></section>
 <div className="ai-disclaimer"><AlertCircle size={14}/><span>Les analyses IA sont une aide à la décision. Vérifiez les informations critiques dans les documents sources.</span></div></>;
}
