import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {requireApiUser} from "@/lib/auth";
import {canValidateDocuments,documentScope} from "@/lib/access";
import {db} from "@/lib/db";
import {assertSameOrigin,audit,badRequest,clientIp,forbidden,unauthorized} from "@/lib/http";
type Context={params:Promise<{id:string}>};const schema=z.object({action:z.enum(["VALIDATE","REJECT","COMMENT","ARCHIVE"]),comment:z.string().trim().max(2000).optional().default("")});
export async function POST(request:NextRequest,{params}:Context){if(!assertSameOrigin(request))return forbidden();const user=await requireApiUser();if(!user)return unauthorized();const{id}=await params;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return badRequest("Action invalide.");const doc=await db.document.findFirst({where:{id,...documentScope(user)},select:{id:true,userId:true,reviewStatus:true,originalName:true}});if(!doc)return NextResponse.json({error:"Document introuvable ou hors de votre périmètre."},{status:404});const{action,comment}=parsed.data;if(action!=="COMMENT"&&!canValidateDocuments(user))return forbidden();if(action==="ARCHIVE"&&user.role!=="ADMIN")return forbidden();if(action==="REJECT"&&!comment)return badRequest("Indiquez la raison du rejet.");
 if(action==="COMMENT"){if(!comment)return badRequest("Le commentaire est vide.");await db.documentComment.create({data:{documentId:id,userId:user.id,content:comment}});await audit(user.id,"DOCUMENT_COMMENTED","Document",id,{comment},clientIp(request));return NextResponse.json({ok:true});}
 const status=action==="VALIDATE"?"VALIDATED":action==="REJECT"?"REJECTED":"ARCHIVED";await db.$transaction(async tx=>{await tx.document.update({where:{id},data:{reviewStatus:status}});if(comment)await tx.documentComment.create({data:{documentId:id,userId:user.id,content:comment}});if(action==="VALIDATE"&&doc.reviewStatus!=="VALIDATED")await tx.scoreEvent.create({data:{userId:doc.userId,documentId:id,awardedById:user.id,points:15,reason:"DOCUMENT_VALIDATED",details:comment||"Information validée"}});if(action==="REJECT"&&doc.reviewStatus!=="REJECTED")await tx.scoreEvent.create({data:{userId:doc.userId,documentId:id,awardedById:user.id,points:-10,reason:"DOCUMENT_REJECTED",details:comment}});if(action!=="ARCHIVE")await tx.alert.create({data:{userId:doc.userId,type:action==="VALIDATE"?"DOCUMENT_VALIDATED":"DOCUMENT_REJECTED",severity:action==="VALIDATE"?"INFO":"WARNING",title:action==="VALIDATE"?"Information validée":"Information rejetée",message:`${doc.originalName}${comment?` — ${comment}`:""}`}})});await audit(user.id,`DOCUMENT_${action}D`,"Document",id,{comment:comment||null},clientIp(request));return NextResponse.json({ok:true,status});}
