"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Tag, Zap, PackageCheck, Database, UploadCloud, Download, ArrowUpRight, Clock3, ClipboardPlus, CheckCheck } from "lucide-react";

type Dashboard = { kpis:{offers:number;flashes:number;restocks:number;recordsTotal:number;documentsPending:number;totalDocuments:number;manualInformations:number;validatedDocuments:number;rejectedDocuments:number;pendingDocuments:number}; unreadAlerts:number; trend:{month:string;offers:number;flashes:number}[]; documentsByWholesaler:{name:string;count:number}[]; documentsByType:{name:string;count:number}[]; topWholesalers:{name:string;count:number}[]; topLabs:{name:string;count:number}[]; topProducts:{name:string;count:number}[]; recent:any[] };
const typeLabel:Record<string,string>={OFFER:"Offre",PROMOTION:"Promotion",FLASH_SALE:"Vente flash",RESTOCK:"Arrivage",DISCOUNT:"Remise",NEW_PRODUCT:"Nouveau",OTHER:"Autre"};
const typeClass:Record<string,string>={OFFER:"badge-blue",PROMOTION:"badge-green",FLASH_SALE:"badge-red",RESTOCK:"badge-orange",DISCOUNT:"badge-gold",NEW_PRODUCT:"badge-blue",OTHER:"badge-gray"};
function number(v:number|undefined){return new Intl.NumberFormat("fr-DZ").format(v||0)}
export default function DashboardPage(){
 const [data,setData]=useState<Dashboard|null>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/dashboard").then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setError("Impossible de charger le tableau de bord."))},[]);
 const rankData=data?.documentsByWholesaler?.length?data.documentsByWholesaler:data?.topWholesalers||[];const max=Math.max(...(rankData.map(x=>x.count)||[1]));
 return <>
  <div className="page-head"><div><h2>Votre veille, en un coup d’œil</h2><p>Suivez les mouvements du marché pharmaceutique et les informations prioritaires.</p></div><div className="page-actions"><a className="btn btn-secondary" href="/api/exports?format=xlsx"><Download size={16}/> Exporter</a><Link className="btn btn-primary" href="/imports"><UploadCloud size={16}/> Nouvel import</Link></div></div>
  {error&&<div className="form-alert">{error}</div>}
  <div className="kpi-grid">
   <div className="card kpi green"><div className="kpi-top"><span className="kpi-icon"><Database size={19}/></span><span className="kpi-delta">Toutes sources</span></div><strong className={!data?"skeleton":""}>{number(data?.kpis.totalDocuments)}</strong><p>Documents et informations</p></div>
   <div className="card kpi orange"><div className="kpi-top"><span className="kpi-icon"><ClipboardPlus size={19}/></span><span className="kpi-delta">Sans IA</span></div><strong className={!data?"skeleton":""}>{number(data?.kpis.manualInformations)}</strong><p>Informations terrain</p></div>
   <div className="card kpi blue"><div className="kpi-top"><span className="kpi-icon"><CheckCheck size={19}/></span><span className="kpi-delta">Workflow</span></div><strong className={!data?"skeleton":""}>{number(data?.kpis.validatedDocuments)}</strong><p>Informations validées</p></div>
   <div className="card kpi gold"><div className="kpi-top"><span className="kpi-icon"><Clock3 size={19}/></span>{(data?.kpis.rejectedDocuments||0)>0&&<span className="kpi-delta">{data?.kpis.rejectedDocuments} rejeté(s)</span>}</div><strong className={!data?"skeleton":""}>{number(data?.kpis.pendingDocuments)}</strong><p>En attente de validation</p></div>
  </div>
  <div className="dashboard-grid">
   <section className="card"><div className="card-head"><div><h3>Évolution des signaux du marché</h3><p>Offres et ventes flash sur les six derniers mois</p></div><div className="chart-legend"><span><i style={{background:"#268a70"}}/>Offres</span><span><i style={{background:"#d67e45"}}/>Ventes flash</span></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data?.trend||[]} margin={{top:10,right:15,left:-22,bottom:0}}><defs><linearGradient id="greenArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#268a70" stopOpacity={.28}/><stop offset="1" stopColor="#268a70" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:9}}/><Tooltip contentStyle={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:10,fontSize:10}}/><Area type="monotone" dataKey="offers" stroke="#268a70" strokeWidth={2.5} fill="url(#greenArea)"/><Area type="monotone" dataKey="flashes" stroke="#d67e45" strokeWidth={2} fill="transparent" strokeDasharray="4 3"/></AreaChart></ResponsiveContainer></div></section>
   <section className="card"><div className="card-head"><div><h3>Grossistes les plus actifs</h3><p>Volume total de signaux</p></div><Link href="/veille"><ArrowUpRight size={17}/></Link></div><div className="rank-list">{(data?rankData:Array(5).fill({name:"Chargement…",count:0})).map((x,i)=><div className="rank-row" key={`${x.name}-${i}`}><span className="rank-number">{i+1}</span><div className="rank-copy"><strong className={!data?"skeleton":""}>{x.name}</strong><div className="rank-bar"><i style={{width:`${Math.max(8,x.count/max*100)}%`}}/></div></div><span className="rank-count">{x.count}</span></div>)}</div></section>
  </div>
  <div className="split-grid">
   <section className="card"><div className="card-head"><div><h3>Dernières informations détectées</h3><p>Résultats les plus récemment structurés par l’IA</p></div><Link className="btn btn-ghost btn-small" href="/veille">Tout afficher <ArrowUpRight size={13}/></Link></div>{data?.recent?.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Produit</th><th>Grossiste / Laboratoire</th><th>Type</th><th>Prix</th><th>Remise</th></tr></thead><tbody>{data.recent.map(r=><tr key={r.id}><td><span className="cell-title">{r.product}</span><small className="cell-sub">{r.wilaya||"Wilaya non précisée"}</small></td><td>{r.wholesaler||"—"}<small className="cell-sub">{r.laboratory||"—"}</small></td><td><span className={`badge ${typeClass[r.offerType]}`}>{typeLabel[r.offerType]}</span></td><td>{r.price?`${r.price} ${r.currency}`:"—"}</td><td><strong>{r.discountPercent?`${r.discountPercent}%`:"—"}</strong></td></tr>)}</tbody></table></div>:<div className="empty-state"><div className="empty-icon"><Database size={22}/></div><h3>Aucune donnée pour le moment</h3><p>Importez votre premier document ; l’IA se chargera de structurer les offres.</p><Link href="/imports" className="btn btn-primary">Importer un document</Link></div>}</section>
   <section className="card"><div className="card-head"><div><h3>Produits les plus signalés</h3><p>Fréquence dans les documents</p></div></div><div className="rank-list product-ranks">{(data?.topProducts||[]).map((x,i)=><div className="rank-row" key={x.name}><span className="rank-number">{i+1}</span><div className="rank-copy"><strong>{x.name}</strong><small className="cell-sub">{x.count} signalement{x.count>1?"s":""}</small></div><span className="badge badge-green">{x.count}</span></div>)}{data&&!data.topProducts.length&&<div className="empty-state"><p>Aucun produit signalé.</p></div>}</div></section>
  </div>
 </>;
}
