"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Download, SlidersHorizontal, ChevronLeft, ChevronRight, Database, FileSpreadsheet, FileText, FileType2 } from "lucide-react";

type RecordItem={id:string;observedAt?:string;wholesaler?:string;laboratory?:string;product:string;price?:string;currency:string;offerType:string;discountPercent?:string;wilaya?:string;region?:string;comments?:string;confidence:number;user:{name:string};document:{originalName:string}};
const labels:Record<string,string>={OFFER:"Offre",PROMOTION:"Promotion",FLASH_SALE:"Vente flash",RESTOCK:"Arrivage",DISCOUNT:"Remise",NEW_PRODUCT:"Nouveau produit",OTHER:"Autre"};
const classes:Record<string,string>={OFFER:"badge-blue",PROMOTION:"badge-green",FLASH_SALE:"badge-red",RESTOCK:"badge-orange",DISCOUNT:"badge-gold",NEW_PRODUCT:"badge-blue",OTHER:"badge-gray"};
export default function WatchPage(){
 const[items,setItems]=useState<RecordItem[]>([]);const[total,setTotal]=useState(0);const[pages,setPages]=useState(1);const[page,setPage]=useState(1);const[search,setSearch]=useState("");const[type,setType]=useState("");const[wilaya,setWilaya]=useState("");const[loading,setLoading]=useState(true);const[exportMenu,setExportMenu]=useState(false);
 const query=useMemo(()=>new URLSearchParams({page:String(page),limit:"20",...(search?{search}:{}),...(type?{type}:{}),...(wilaya?{wilaya}:{})}),[page,search,type,wilaya]);
 useEffect(()=>{const t=setTimeout(()=>{setLoading(true);fetch(`/api/records?${query}`).then(r=>r.json()).then(d=>{setItems(d.items||[]);setTotal(d.total||0);setPages(d.pages||1)}).finally(()=>setLoading(false))},250);return()=>clearTimeout(t)},[query]);
 function reset(){setSearch("");setType("");setWilaya("");setPage(1)}
 const exportQuery=`type=${encodeURIComponent(type)}`;
 return <><div className="page-head"><div><h2>Données de veille</h2><p>Explorez toutes les informations structurées et autorisées dans votre espace.</p></div><div className="export-wrap"><button className="btn btn-primary" onClick={()=>setExportMenu(!exportMenu)}><Download size={15}/> Exporter</button>{exportMenu&&<div className="export-menu"><a href={`/api/exports?format=xlsx&${exportQuery}`}><FileSpreadsheet size={16}/><span><b>Excel</b><small>Tableau exploitable .xlsx</small></span></a><a href={`/api/exports?format=pdf&${exportQuery}`}><FileText size={16}/><span><b>PDF</b><small>Rapport de synthèse</small></span></a><a href={`/api/exports?format=docx&${exportQuery}`}><FileType2 size={16}/><span><b>Word</b><small>Document éditable .docx</small></span></a></div>}</div></div>
 <section className={`card ${loading?"loading":""}`}><div className="filters"><div className="search-box"><Search size={17}/><input className="input" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Rechercher un produit, grossiste, laboratoire…"/></div><select className="select" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">Tous les types</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input className="input wilaya-filter" value={wilaya} onChange={e=>{setWilaya(e.target.value);setPage(1)}} placeholder="Wilaya"/>{(search||type||wilaya)&&<button className="btn btn-ghost btn-small" onClick={reset}>Réinitialiser</button>}<span className="filter-count"><SlidersHorizontal size={13}/>{total} résultat{total>1?"s":""}</span></div>
 {items.length?<div className="table-scroll"><table className="data-table watch-table"><thead><tr><th>Date</th><th>Produit</th><th>Grossiste</th><th>Laboratoire</th><th>Type d’offre</th><th>Prix</th><th>Remise</th><th>Wilaya</th><th>Confiance IA</th></tr></thead><tbody>{items.map(r=><tr key={r.id} title={r.comments||""}><td>{r.observedAt?new Date(r.observedAt).toLocaleDateString("fr-DZ"):"—"}</td><td><span className="cell-title">{r.product}</span><small className="cell-sub">{r.document.originalName}</small></td><td>{r.wholesaler||"—"}</td><td>{r.laboratory||"—"}</td><td><span className={`badge ${classes[r.offerType]}`}>{labels[r.offerType]}</span></td><td><strong>{r.price?`${r.price} ${r.currency}`:"—"}</strong></td><td>{r.discountPercent?<span className="discount-value">−{r.discountPercent}%</span>:"—"}</td><td>{r.wilaya||"—"}<small className="cell-sub">{r.region||""}</small></td><td><span className="confidence"><i style={{width:`${Math.round(r.confidence*100)}%`}}/><small>{Math.round(r.confidence*100)}%</small></span></td></tr>)}</tbody></table></div>:!loading&&<div className="empty-state"><div className="empty-icon"><Database size={22}/></div><h3>Aucun résultat</h3><p>Modifiez vos filtres ou importez de nouveaux documents.</p>{(search||type||wilaya)&&<button className="btn btn-secondary" onClick={reset}>Réinitialiser les filtres</button>}</div>}
 <div className="pagination"><span>Page {page} sur {pages} • {total} données</span><div className="pagination-buttons"><button className="icon-btn" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><button className="icon-btn" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div></section></>;
}
