"use client";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { WILAYAS,REGION_LABELS } from "@/lib/algeria";
import { UploadCloud, FileText, FileSpreadsheet, FileImage, FileType2, CheckCircle2, AlertCircle, BrainCircuit, Database, BellRing, RefreshCw, X, Info, Download, Trash2, CheckCheck, MessageSquare, Ban, Save, FileCheck2 } from "lucide-react";

type Doc={id:string;userId:string;user:{name:string};originalName:string;size:number;status:"WAITING_AI"|"PENDING"|"PROCESSING"|"COMPLETED"|"FAILED";errorMessage?:string;createdAt:string;wholesaler?:string;documentType:string;priority:string;reviewStatus:string;_count:{records:number}};
type Uploading={id:string;name:string;progress:number;attempt:number;error?:string};type Draft={id:string;title:string;metadata:any;updatedAt:string;files:{id:string;originalName:string;size:number}[]};
type Metadata={wholesaler:string;customWholesaler:string;documentType:string;customDocumentType:string;documentDate:string;receivedAt:string;region:string;wilaya:string;product:string;laboratory:string;comments:string;confidentiality:string;priority:string};
const today=()=>new Date().toISOString().slice(0,10);
const wholesalers=["Hydra Pharm","Somepharm","Pharmainvest","Bigdis","Vecopharm","LDM","Biocare","BPO","Milinum","Watson","Chark Pharm"];
const documentTypes:Record<string,string>={FLASH_SALE:"Vente Flash",RESTOCK:"Arrivage",COMMERCIAL_PROPOSAL:"Proposition commerciale",QUOTA:"Quota",PROMOTION:"Promotion",CONVENTION:"Convention",REBATE:"Ristourne",EXCEPTIONAL_DISCOUNT:"Remise exceptionnelle",PRICING:"Tarifs",CATALOG:"Catalogue",STOCKOUT:"Rupture de stock",PRODUCT_LAUNCH:"Lancement de produit",COMMERCIAL_COMMUNICATION:"Communication commerciale",LAB_INFORMATION:"Information laboratoire",LETTER:"Courrier",EMAIL:"E-mail",OTHER:"Autre"};
const initial:Metadata={wholesaler:"",customWholesaler:"",documentType:"",customDocumentType:"",documentDate:today(),receivedAt:today(),region:"",wilaya:"",product:"",laboratory:"",comments:"",confidentiality:"INTERNAL",priority:"NORMAL"};
function icon(name:string){if(/\.xlsx?$|\.csv$/i.test(name))return <FileSpreadsheet size={19}/>;if(/\.(png|jpe?g|webp)$/i.test(name))return <FileImage size={19}/>;if(/\.docx$/i.test(name))return <FileType2 size={19}/>;return <FileText size={19}/>}
function size(n:number){return n>1048576?`${(n/1048576).toFixed(1)} Mo`:`${Math.ceil(n/1024)} Ko`}
const reviewLabels:Record<string,string>={PENDING:"En attente",PENDING_AI:"En attente IA",NEEDS_REVIEW:"À contrôler",MODIFIED:"Modifiée",VALIDATED:"Validée",REJECTED:"Rejetée",ARCHIVED:"Archivée"};
const statusInfo={WAITING_AI:["En attente IA","badge-gray"],PENDING:["En attente","badge-orange"],PROCESSING:["Analyse IA","badge-orange"],COMPLETED:["Terminé","badge-green"],FAILED:["Échec","badge-red"]} as const;
export default function ImportsPage(){
 const ref=useRef<HTMLInputElement>(null);const[drag,setDrag]=useState(false);const[uploads,setUploads]=useState<Uploading[]>([]);const[pendingFiles,setPendingFiles]=useState<File[]>([]);const[drafts,setDrafts]=useState<Draft[]>([]);const[activeDraftId,setActiveDraftId]=useState("");const[docs,setDocs]=useState<Doc[]>([]);const[toast,setToast]=useState("");const[metadata,setMetadata]=useState<Metadata>(initial);const[selectedTypeId,setSelectedTypeId]=useState("");const[formError,setFormError]=useState("");const[me,setMe]=useState<{id:string;role:string;permissions:{canDeleteOwn:boolean}}|null>(null);const[catalogWholesalers,setCatalogWholesalers]=useState(wholesalers);const[catalogLabs,setCatalogLabs]=useState<string[]>([]);const[catalogWilayas,setCatalogWilayas]=useState<any[]>(WILAYAS);const[catalogTypes,setCatalogTypes]=useState<any[]>([]);
 const load=useCallback(()=>fetch("/api/documents?limit=15").then(r=>r.json()).then(d=>setDocs(d.items||[])).catch(()=>undefined),[]);const loadDrafts=useCallback(()=>fetch("/api/import-drafts").then(r=>r.json()).then(d=>setDrafts(d.items||[])).catch(()=>undefined),[]);
 useEffect(()=>{load();loadDrafts();fetch("/api/auth/me").then(r=>r.json()).then(d=>setMe(d.user||null));fetch("/api/public/references").then(r=>r.json()).then(d=>{d.wholesalers?.length&&setCatalogWholesalers(d.wholesalers.map((x:any)=>x.name));d.laboratories?.length&&setCatalogLabs(d.laboratories.map((x:any)=>x.name));d.wilayas?.length&&setCatalogWilayas(d.wilayas);d.documentTypes?.length&&setCatalogTypes(d.documentTypes)});const t=setInterval(load,5000);return()=>clearInterval(t)},[load,loadDrafts]);
 function valid(){if(!metadata.wholesaler)return"Sélectionnez le grossiste avant l’import.";if(metadata.wholesaler==="OTHER"&&!metadata.customWholesaler.trim())return"Précisez le nom du grossiste.";if(!metadata.documentType)return"Sélectionnez le type de document.";if(metadata.documentType==="OTHER"&&!metadata.customDocumentType.trim())return"Précisez le type de document.";return""}
 function upload(file:File,id:string,attempt=0){
  const form=new FormData();form.append("file",file);Object.entries(metadata).forEach(([k,v])=>form.append(k,v));
  const xhr=new XMLHttpRequest();xhr.open("POST","/api/documents");xhr.upload.onprogress=e=>{if(e.lengthComputable)setUploads(u=>u.map(x=>x.id===id?{...x,progress:Math.round(e.loaded/e.total*100),attempt}:x))};
  const retry=(message:string)=>{if(attempt<2){setUploads(u=>u.map(x=>x.id===id?{...x,error:`${message} — nouvelle tentative ${attempt+2}/3`}:x));setTimeout(()=>upload(file,id,attempt+1),1500*(attempt+1));}else setUploads(u=>u.map(x=>x.id===id?{...x,error:message}:x))};
  xhr.onload=()=>{let data:any={};try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300){setUploads(u=>u.filter(x=>x.id!==id));setToast(`${file.name} a été enregistré${data.document?.status==="WAITING_AI"?" et attend l’activation de l’IA":" pour analyse"}.`);load();setTimeout(()=>setToast(""),5000)}else if(xhr.status>=500)retry(data.error||`Erreur serveur ${xhr.status}`);else setUploads(u=>u.map(x=>x.id===id?{...x,error:data.error||"Échec de l’import"}:x))};xhr.onerror=()=>retry("Connexion interrompue");xhr.ontimeout=()=>retry("Délai de téléversement dépassé");xhr.timeout=120000;xhr.send(form);
 }
 function files(list:FileList|null){if(!list)return;setPendingFiles(current=>[...current,...Array.from(list)].slice(0,10));setFormError("")}
 function drop(e:DragEvent){e.preventDefault();setDrag(false);files(e.dataTransfer.files)}
 async function validateAndSave(){const error=valid()||(!pendingFiles.length&&!activeDraftId&&(!metadata.product.trim()||!metadata.comments.trim())?"Sans fichier, renseignez le produit et le commentaire/description.":"");if(error){setFormError(error);document.querySelector(".metadata-card")?.scrollIntoView({behavior:"smooth"});return}setFormError("");if(activeDraftId){await fetch(`/api/import-drafts/${activeDraftId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({metadata,title:metadata.product||metadata.documentType})});const r=await fetch(`/api/import-drafts/${activeDraftId}/validate`,{method:"POST"});const d=await r.json();setToast(r.ok?"✅ Importation réalisée avec succès.":`❌ ${d.error||"L’importation a échoué."}`);if(r.ok){setActiveDraftId("");setMetadata(initial);setSelectedTypeId("");load();loadDrafts()}return}if(pendingFiles.length){pendingFiles.forEach(file=>{const id=crypto.randomUUID();setUploads(u=>[{id,name:file.name,progress:0,attempt:0},...u]);upload(file,id)});setPendingFiles([]);return}const f=new FormData();f.append("wholesaler",metadata.wholesaler==="OTHER"?metadata.customWholesaler:metadata.wholesaler);f.append("entityType","WHOLESALER");f.append("entityName",metadata.customWholesaler);f.append("laboratory",metadata.laboratory);f.append("product",metadata.product);f.append("documentType",metadata.documentType);f.append("customDocumentType",metadata.customDocumentType);f.append("region",metadata.region);f.append("wilaya",metadata.wilaya);f.append("date",metadata.documentDate||today());f.append("description",metadata.comments);f.append("source","Saisie import intelligent");f.append("priority",metadata.priority);f.append("confidence","80");f.append("isStrategic","false");const r=await fetch("/api/manual-information",{method:"POST",body:f});const d=await r.json();setToast(r.ok?"✅ Importation réalisée avec succès.":`❌ ${d.error||"L’importation a échoué."}`);if(r.ok){setMetadata(initial);setSelectedTypeId("");load()}}
 async function saveDraft(){const form=new FormData();form.append("metadata",JSON.stringify(metadata));form.append("title",metadata.product||metadata.customDocumentType||metadata.documentType||"Brouillon");pendingFiles.forEach(f=>form.append("files",f));if(activeDraftId){const r=await fetch(`/api/import-drafts/${activeDraftId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({metadata,title:metadata.product||metadata.documentType||"Brouillon"})});const d=await r.json();setToast(r.ok?"💾 Brouillon mis à jour.":d.error);loadDrafts();return}const r=await fetch("/api/import-drafts",{method:"POST",body:form});const d=await r.json();setToast(r.ok?"💾 Brouillon enregistré dans Supabase.":d.error||"Enregistrement impossible.");if(r.ok){setPendingFiles([]);loadDrafts()}}
 function resumeDraft(d:Draft){setActiveDraftId(d.id);setMetadata({...initial,...d.metadata});setPendingFiles([]);setSelectedTypeId("");setToast(`Brouillon « ${d.title} » chargé. Complétez puis validez.`);document.querySelector(".metadata-card")?.scrollIntoView({behavior:"smooth"})}
 async function deleteDraft(id:string){if(!confirm("Supprimer ce brouillon ?"))return;await fetch(`/api/import-drafts/${id}`,{method:"DELETE"});if(activeDraftId===id)setActiveDraftId("");loadDrafts()}
 async function retry(id:string){const r=await fetch(`/api/documents/${id}/retry`,{method:"POST"});const d=await r.json();setToast(r.ok?"Analyse relancée.":d.error||"Relance impossible.");load();setTimeout(()=>setToast(""),5000)}
 async function validateDocument(id:string){const r=await fetch(`/api/documents/${id}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"VALIDATE"})});const d=await r.json();setToast(r.ok?"Document validé.":d.error||"Validation impossible.");load();setTimeout(()=>setToast(""),4000)}
 async function workflow(id:string,action:"REJECT"|"COMMENT"){const comment=prompt(action==="REJECT"?"Raison du rejet :":"Votre commentaire :");if(!comment)return;const r=await fetch(`/api/documents/${id}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,comment})});const d=await r.json();setToast(r.ok?(action==="REJECT"?"Information rejetée.":"Commentaire ajouté."):d.error||"Action impossible.");load();setTimeout(()=>setToast(""),4000)}
 async function removeDocument(id:string){if(!confirm("Supprimer définitivement ce document et ses données ?"))return;const r=await fetch(`/api/documents/${id}`,{method:"DELETE"});const d=await r.json();setToast(r.ok?"Document supprimé.":d.error||"Suppression impossible.");load();setTimeout(()=>setToast(""),4000)}
 return <><div className="page-head"><div><h2>Importation intelligente</h2><p>Qualifiez les documents avant l’import pour améliorer le classement et la fiabilité de l’extraction.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Actualiser</button></div>
 <section className="card metadata-card"><div className="card-head"><div><h3>1. Informations du document</h3><p>Le grossiste et le type de document sont obligatoires</p></div><Info size={19}/></div><div className="card-body"><div className="metadata-grid">
  <div className="field"><label>Grossiste *</label><select className="select" value={metadata.wholesaler} onChange={e=>setMetadata({...metadata,wholesaler:e.target.value})}><option value="">Sélectionner…</option>{catalogWholesalers.map(x=><option key={x}>{x}</option>)}<option value="OTHER">Autre</option></select></div>
  {metadata.wholesaler==="OTHER"&&<div className="field"><label>Nom du grossiste *</label><input className="input" value={metadata.customWholesaler} onChange={e=>setMetadata({...metadata,customWholesaler:e.target.value})}/></div>}
  <div className="field"><label>Type de document *</label><select className="select" value={catalogTypes.length?selectedTypeId:metadata.documentType} onChange={e=>{if(catalogTypes.length){setSelectedTypeId(e.target.value);const t=catalogTypes.find((x:any)=>x.id===e.target.value);const code=(t?.metadata as any)?.prismaCode||"OTHER";setMetadata({...metadata,documentType:code,customDocumentType:code==="OTHER"&&t?.code!=="OTHER"?t?.name||"":""})}else setMetadata({...metadata,documentType:e.target.value})}}><option value="">Sélectionner…</option>{catalogTypes.length?catalogTypes.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>):Object.entries(documentTypes).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>
  {metadata.documentType==="OTHER"&&!metadata.customDocumentType&&<div className="field"><label>Type personnalisé *</label><input className="input" value={metadata.customDocumentType} onChange={e=>setMetadata({...metadata,customDocumentType:e.target.value})}/></div>}
  <div className="field"><label>Date du document</label><input type="date" className="input" value={metadata.documentDate} onChange={e=>setMetadata({...metadata,documentDate:e.target.value})}/></div>
  <div className="field"><label>Date de réception</label><input type="date" className="input" value={metadata.receivedAt} onChange={e=>setMetadata({...metadata,receivedAt:e.target.value})}/></div>
  <div className="field"><label>Wilaya</label><select className="select" value={metadata.wilaya} onChange={e=>{const w=catalogWilayas.find((x:any)=>x.name===e.target.value);setMetadata({...metadata,wilaya:e.target.value,region:w?.region||""})}}><option value="">Sélectionner…</option>{catalogWilayas.map((w:any)=><option value={w.name} key={w.code}>{String(w.code).padStart(2,"0")} — {w.name}</option>)}</select></div>
  <div className="field"><label>Région automatique</label><input className="input" value={(REGION_LABELS as any)[metadata.region]||"Choisissez une wilaya"} readOnly/></div>
  <div className="field"><label>Laboratoire</label><select className="select" value={metadata.laboratory} onChange={e=>setMetadata({...metadata,laboratory:e.target.value})}><option value="">Sélectionner…</option>{catalogLabs.map(x=><option key={x}>{x}</option>)}</select></div>
  <div className="field"><label>Produit (obligatoire sans fichier)</label><input className="input" value={metadata.product} onChange={e=>setMetadata({...metadata,product:e.target.value})}/></div>
  <div className="field"><label>Confidentialité</label><select className="select" value={metadata.confidentiality} onChange={e=>setMetadata({...metadata,confidentiality:e.target.value})}><option value="INTERNAL">Interne</option><option value="CONFIDENTIAL">Confidentiel</option><option value="HIGHLY_CONFIDENTIAL">Hautement confidentiel</option></select></div>
  <div className="field"><label>Priorité</label><select className="select" value={metadata.priority} onChange={e=>setMetadata({...metadata,priority:e.target.value})}><option value="LOW">Faible</option><option value="NORMAL">Normale</option><option value="HIGH">Haute</option><option value="URGENT">Urgente</option></select></div>
  <div className="field span-all"><label>Commentaires</label><textarea className="textarea" value={metadata.comments} onChange={e=>setMetadata({...metadata,comments:e.target.value})} placeholder="Contexte, commercial concerné, conditions particulières…"/></div>
 </div>{formError&&<div className="form-alert metadata-error"><AlertCircle size={16}/>{formError}</div>}{activeDraftId&&<div className="draft-active"><Save size={14}/> Brouillon en cours de modification</div>}<div className="import-validation-actions"><button className="btn btn-secondary" type="button" onClick={saveDraft}><Save size={16}/> Enregistrer comme brouillon</button><button className="btn btn-primary" type="button" onClick={validateAndSave}><FileCheck2 size={16}/> Valider et enregistrer</button></div></div></section>
 <section className="upload-layout"><div className="card upload-card"><div className={`drop-zone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>ref.current?.click()}><input ref={ref} hidden type="file" multiple accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>{files(e.target.files);e.target.value=""}}/><div className="drop-icon"><UploadCloud size={29}/></div><h3>2. Déposez vos documents ici</h3><p>Jusqu’à 10 fichiers avec les métadonnées ci-dessus</p><button className="btn btn-primary" type="button">Choisir des fichiers</button><small>PDF, Word, Excel, CSV, images ou texte • 8 Mo maximum</small></div>
 {pendingFiles.length>0&&<div className="pending-files"><strong>{pendingFiles.length} fichier(s) prêt(s) à être validé(s)</strong>{pendingFiles.map((f,i)=><div key={`${f.name}-${i}`}><span className="file-icon">{icon(f.name)}</span><span><b>{f.name}</b><small>{size(f.size)}</small></span><button className="icon-btn" onClick={()=>setPendingFiles(x=>x.filter((_,n)=>n!==i))}><X size={14}/></button></div>)}</div>}
 {uploads.length>0&&<div className="uploading-list">{uploads.map(u=><div className="upload-row" key={u.id}><span className="file-icon">{icon(u.name)}</span><div className="upload-info"><strong>{u.name}</strong>{u.error?<small className="upload-error">{u.error}</small>:<><div className="progress"><i style={{width:`${u.progress}%`}}/></div><small>{u.progress<100?`Téléversement ${u.progress}%`:"Enregistrement…"}</small></>}</div><button onClick={()=>setUploads(x=>x.filter(y=>y.id!==u.id))}><X size={15}/></button></div>)}</div>}</div>
 <aside className="card process-card"><div className="card-head"><div><h3>Traitement intelligent</h3><p>Du document à la donnée exploitable</p></div><BrainCircuit size={21}/></div><div className="process-steps"><div><span><UploadCloud size={17}/></span><p><strong>1. Import qualifié</strong><small>Métadonnées confirmées par l’utilisateur.</small></p></div><i/><div><span><BrainCircuit size={17}/></span><p><strong>2. OCR et analyse IA</strong><small>Tableaux, scans, images et texte.</small></p></div><i/><div><span><Database size={17}/></span><p><strong>3. Structuration</strong><small>Produits, prix, UG, quotas et conditions.</small></p></div><i/><div><span><BellRing size={17}/></span><p><strong>4. Contrôle et alertes</strong><small>Validation humaine avant exploitation.</small></p></div></div></aside></section>
 {drafts.length>0&&<section className="card drafts-card"><div className="card-head"><div><h3>Mes brouillons</h3><p>Reprenez une saisie incomplète sans perdre les fichiers déjà stockés.</p></div><span className="badge badge-gray">{drafts.length}</span></div><div className="draft-list">{drafts.map(d=><article key={d.id}><span className="file-icon"><Save size={16}/></span><div><strong>{d.title}</strong><small>{d.files.length} fichier(s) • modifié le {new Date(d.updatedAt).toLocaleString("fr-DZ")}</small></div><button className="btn btn-secondary btn-small" onClick={()=>resumeDraft(d)}>Reprendre</button><button className="icon-btn delete-action" onClick={()=>deleteDraft(d.id)}><Trash2 size={14}/></button></article>)}</div></section>}
 <section className="card imports-history"><div className="card-head"><div><h3>Imports récents</h3><p>Suivez l’état d’analyse et relancez les échecs</p></div></div>{docs.length?<div className="table-scroll"><table className="data-table import-v2-table"><thead><tr><th>Document</th><th>Grossiste</th><th>Type</th><th>Importé par</th><th>Envoi</th><th>Données</th><th>Statut</th><th/></tr></thead><tbody>{docs.map(d=>{const info=statusInfo[d.status];return <tr key={d.id}><td><span className="document-cell"><i className="file-icon">{icon(d.originalName)}</i><span><b>{d.originalName}</b><small>{size(d.size)} • priorité {d.priority?.toLowerCase()}</small></span></span></td><td>{d.wholesaler||"—"}</td><td>{documentTypes[d.documentType]||d.documentType}</td><td>{d.user?.name||"—"}</td><td>{new Date(d.createdAt).toLocaleString("fr-DZ",{dateStyle:"short",timeStyle:"short"})}</td><td>{d._count.records||"—"}</td><td><span className={`badge ${info[1]}`}>{d.status==="COMPLETED"?<CheckCircle2 size={12}/>:d.status==="FAILED"?<AlertCircle size={12}/>:<RefreshCw className={d.status==="PROCESSING"?"spin":""} size={12}/>} {info[0]}</span><small className="cell-sub">Workflow : {reviewLabels[d.reviewStatus]||d.reviewStatus}</small>{d.errorMessage&&<small className="cell-sub import-error" title={d.errorMessage}>{d.errorMessage}</small>}</td><td><div className="document-actions"><a className="icon-btn" href={`/api/documents/${d.id}/download`} title="Télécharger"><Download size={14}/></a>{["FAILED","WAITING_AI"].includes(d.status)&&<button className="icon-btn" title="Relancer" onClick={()=>retry(d.id)}><RefreshCw size={14}/></button>}<button className="icon-btn" title="Commenter" onClick={()=>workflow(d.id,"COMMENT")}><MessageSquare size={14}/></button>{me&&["ADMIN","SUPERVISOR"].includes(me.role)&&d.reviewStatus!=="VALIDATED"&&<><button className="icon-btn" title="Valider" onClick={()=>validateDocument(d.id)}><CheckCheck size={14}/></button><button className="icon-btn delete-action" title="Rejeter" onClick={()=>workflow(d.id,"REJECT")}><Ban size={14}/></button></>}{me&&(me.role==="ADMIN"||(me.role==="DELEGATE"&&me.id===d.userId&&me.permissions.canDeleteOwn))&&<button className="icon-btn delete-action" title="Supprimer" onClick={()=>removeDocument(d.id)}><Trash2 size={14}/></button>}</div></td></tr>})}</tbody></table></div>:<div className="empty-state"><div className="empty-icon"><FileText size={21}/></div><h3>Aucun document importé</h3><p>Qualifiez puis importez votre premier document.</p></div>}</section>
 {toast&&<div className="toast success"><CheckCircle2 size={18}/><div><strong>Information</strong><p>{toast}</p></div></div>}</>;
}
