"use client";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { UploadCloud, FileText, FileSpreadsheet, FileImage, FileType2, CheckCircle2, AlertCircle, BrainCircuit, Database, BellRing, RefreshCw, X } from "lucide-react";

type Doc={id:string;originalName:string;size:number;status:"PENDING"|"PROCESSING"|"COMPLETED"|"FAILED";errorMessage?:string;createdAt:string;_count:{records:number}};
type Uploading={id:string;name:string;progress:number;error?:string};
function icon(name:string){if(/\.xlsx?$|\.csv$/i.test(name))return <FileSpreadsheet size={19}/>;if(/\.(png|jpe?g|webp)$/i.test(name))return <FileImage size={19}/>;if(/\.docx$/i.test(name))return <FileType2 size={19}/>;return <FileText size={19}/>}
function size(n:number){return n>1048576?`${(n/1048576).toFixed(1)} Mo`:`${Math.ceil(n/1024)} Ko`}
export default function ImportsPage(){
 const ref=useRef<HTMLInputElement>(null);const[drag,setDrag]=useState(false);const[uploads,setUploads]=useState<Uploading[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[toast,setToast]=useState("");
 const load=useCallback(()=>fetch("/api/documents?limit=12").then(r=>r.json()).then(d=>setDocs(d.items||[])).catch(()=>undefined),[]);
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);
 function send(file:File){const id=crypto.randomUUID();setUploads(u=>[{id,name:file.name,progress:0},...u]);const form=new FormData();form.append("file",file);const xhr=new XMLHttpRequest();xhr.open("POST","/api/documents");xhr.upload.onprogress=e=>{if(e.lengthComputable)setUploads(u=>u.map(x=>x.id===id?{...x,progress:Math.round(e.loaded/e.total*100)}:x))};xhr.onload=()=>{let data:any={};try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300){setUploads(u=>u.filter(x=>x.id!==id));setToast(`${file.name} a été envoyé pour analyse.`);load();setTimeout(()=>setToast(""),4000)}else setUploads(u=>u.map(x=>x.id===id?{...x,error:data.error||"Échec de l’import"}:x))};xhr.onerror=()=>setUploads(u=>u.map(x=>x.id===id?{...x,error:"Erreur réseau"}:x));xhr.send(form)}
 function files(list:FileList|null){if(!list)return;Array.from(list).slice(0,10).forEach(send)}
 function drop(e:DragEvent){e.preventDefault();setDrag(false);files(e.dataTransfer.files)}
 return <><div className="page-head"><div><h2>Importer des informations</h2><p>Déposez vos documents ; l’IA extrait, structure et classe automatiquement chaque information.</p></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={15}/> Actualiser</button></div>
 <section className="upload-layout"><div className="card upload-card"><div className={`drop-zone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>ref.current?.click()}><input ref={ref} hidden type="file" multiple accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>{files(e.target.files);e.target.value=""}}/><div className="drop-icon"><UploadCloud size={29}/></div><h3>Déposez vos documents ici</h3><p>ou cliquez pour parcourir vos fichiers</p><button className="btn btn-primary" type="button">Choisir des fichiers</button><small>PDF, Word, Excel, CSV, images ou texte • 25 Mo maximum par fichier</small></div>
 {uploads.length>0&&<div className="uploading-list">{uploads.map(u=><div className="upload-row" key={u.id}><span className="file-icon">{icon(u.name)}</span><div className="upload-info"><strong>{u.name}</strong>{u.error?<small className="upload-error">{u.error}</small>:<><div className="progress"><i style={{width:`${u.progress}%`}}/></div><small>{u.progress<100?`Téléversement ${u.progress}%`:"Mise en file d’analyse…"}</small></>}</div><button onClick={()=>setUploads(x=>x.filter(y=>y.id!==u.id))}><X size={15}/></button></div>)}</div>}</div>
 <aside className="card process-card"><div className="card-head"><div><h3>Traitement intelligent</h3><p>Du document à la donnée exploitable</p></div><BrainCircuit size={21}/></div><div className="process-steps"><div><span><UploadCloud size={17}/></span><p><strong>1. Import sécurisé</strong><small>Le fichier est chiffré et stocké dans votre espace.</small></p></div><i/><div><span><BrainCircuit size={17}/></span><p><strong>2. Analyse par l’IA</strong><small>Lecture du contenu et extraction des champs clés.</small></p></div><i/><div><span><Database size={17}/></span><p><strong>3. Structuration</strong><small>Classement par produit, date, région et offre.</small></p></div><i/><div><span><BellRing size={17}/></span><p><strong>4. Alertes automatiques</strong><small>Notification des signaux importants détectés.</small></p></div></div></aside></section>
 <section className="card imports-history"><div className="card-head"><div><h3>Imports récents</h3><p>Suivez l’état d’analyse de vos documents</p></div></div>{docs.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Document</th><th>Taille</th><th>Envoi</th><th>Données extraites</th><th>Statut</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><span className="document-cell"><i className="file-icon">{icon(d.originalName)}</i><span><b>{d.originalName}</b>{d.errorMessage&&<small title={d.errorMessage}>{d.errorMessage}</small>}</span></span></td><td>{size(d.size)}</td><td>{new Date(d.createdAt).toLocaleString("fr-DZ",{dateStyle:"short",timeStyle:"short"})}</td><td>{d._count.records||"—"}</td><td><span className={`badge ${d.status==="COMPLETED"?"badge-green":d.status==="FAILED"?"badge-red":"badge-orange"}`}>{d.status==="COMPLETED"?<CheckCircle2 size={12}/>:d.status==="FAILED"?<AlertCircle size={12}/>:<RefreshCw className={d.status==="PROCESSING"?"spin":""} size={12}/>} {{PENDING:"En attente",PROCESSING:"Analyse IA",COMPLETED:"Terminé",FAILED:"Échec"}[d.status]}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><div className="empty-icon"><FileText size={21}/></div><h3>Aucun document importé</h3><p>Vos documents et leur état d’analyse apparaîtront ici.</p></div>}</section>
 {toast&&<div className="toast success"><CheckCircle2 size={18}/><div><strong>Document reçu</strong><p>{toast}</p></div></div>}</>;
}
