-- Seed the official 69-wilaya reference (Loi 26-06, 2026) and document types.
INSERT INTO "reference_entities" ("id","type","name","code","region","sortOrder","metadata","aliases","updatedAt") VALUES
('wilaya-01','WILAYA','Adrar','01','SUD',1,'{"nameAr": "أدرار", "iso": "DZ-01"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-02','WILAYA','Chlef','02','OUEST',2,'{"nameAr": "الشلف", "iso": "DZ-02"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-03','WILAYA','Laghouat','03','CENTRE',3,'{"nameAr": "الأغواط", "iso": "DZ-03"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-04','WILAYA','Oum El Bouaghi','04','EST',4,'{"nameAr": "أم البواقي", "iso": "DZ-04"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-05','WILAYA','Batna','05','EST',5,'{"nameAr": "باتنة", "iso": "DZ-05"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-06','WILAYA','Béjaïa','06','EST',6,'{"nameAr": "بجاية", "iso": "DZ-06"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-07','WILAYA','Biskra','07','EST',7,'{"nameAr": "بسكرة", "iso": "DZ-07"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-08','WILAYA','Béchar','08','SUD',8,'{"nameAr": "بشار", "iso": "DZ-08"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-09','WILAYA','Blida','09','CENTRE',9,'{"nameAr": "البليدة", "iso": "DZ-09"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-10','WILAYA','Bouira','10','CENTRE',10,'{"nameAr": "البويرة", "iso": "DZ-10"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-11','WILAYA','Tamanrasset','11','SUD',11,'{"nameAr": "تمنراست", "iso": "DZ-11"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-12','WILAYA','Tébessa','12','EST',12,'{"nameAr": "تبسة", "iso": "DZ-12"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-13','WILAYA','Tlemcen','13','OUEST',13,'{"nameAr": "تلمسان", "iso": "DZ-13"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-14','WILAYA','Tiaret','14','OUEST',14,'{"nameAr": "تيارت", "iso": "DZ-14"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-15','WILAYA','Tizi Ouzou','15','EST',15,'{"nameAr": "تيزي وزو", "iso": "DZ-15"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-16','WILAYA','Alger','16','CENTRE',16,'{"nameAr": "الجزائر", "iso": "DZ-16"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-17','WILAYA','Djelfa','17','CENTRE',17,'{"nameAr": "الجلفة", "iso": "DZ-17"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-18','WILAYA','Jijel','18','EST',18,'{"nameAr": "جيجل", "iso": "DZ-18"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-19','WILAYA','Sétif','19','EST',19,'{"nameAr": "سطيف", "iso": "DZ-19"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-20','WILAYA','Saïda','20','OUEST',20,'{"nameAr": "سعيدة", "iso": "DZ-20"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-21','WILAYA','Skikda','21','EST',21,'{"nameAr": "سكيكدة", "iso": "DZ-21"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-22','WILAYA','Sidi Bel Abbès','22','OUEST',22,'{"nameAr": "سيدي بلعباس", "iso": "DZ-22"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-23','WILAYA','Annaba','23','EST',23,'{"nameAr": "عنابة", "iso": "DZ-23"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-24','WILAYA','Guelma','24','EST',24,'{"nameAr": "قالمة", "iso": "DZ-24"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-25','WILAYA','Constantine','25','EST',25,'{"nameAr": "قسنطينة", "iso": "DZ-25"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-26','WILAYA','Médéa','26','CENTRE',26,'{"nameAr": "المدية", "iso": "DZ-26"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-27','WILAYA','Mostaganem','27','OUEST',27,'{"nameAr": "مستغانم", "iso": "DZ-27"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-28','WILAYA','M''Sila','28','CENTRE',28,'{"nameAr": "المسيلة", "iso": "DZ-28"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-29','WILAYA','Mascara','29','OUEST',29,'{"nameAr": "معسكر", "iso": "DZ-29"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-30','WILAYA','Ouargla','30','SUD',30,'{"nameAr": "ورقلة", "iso": "DZ-30"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-31','WILAYA','Oran','31','OUEST',31,'{"nameAr": "وهران", "iso": "DZ-31"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-32','WILAYA','El Bayadh','32','OUEST',32,'{"nameAr": "البيض", "iso": "DZ-32"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-33','WILAYA','Illizi','33','SUD',33,'{"nameAr": "إليزي", "iso": "DZ-33"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-34','WILAYA','Bordj Bou Arréridj','34','EST',34,'{"nameAr": "برج بوعريريج", "iso": "DZ-34"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-35','WILAYA','Boumerdès','35','CENTRE',35,'{"nameAr": "بومرداس", "iso": "DZ-35"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-36','WILAYA','El Tarf','36','EST',36,'{"nameAr": "الطارف", "iso": "DZ-36"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-37','WILAYA','Tindouf','37','SUD',37,'{"nameAr": "تيندوف", "iso": "DZ-37"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-38','WILAYA','Tissemsilt','38','OUEST',38,'{"nameAr": "تيسمسيلت", "iso": "DZ-38"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-39','WILAYA','El Oued','39','SUD',39,'{"nameAr": "الوادي", "iso": "DZ-39"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-40','WILAYA','Khenchela','40','EST',40,'{"nameAr": "خنشلة", "iso": "DZ-40"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-41','WILAYA','Souk Ahras','41','EST',41,'{"nameAr": "سوق أهراس", "iso": "DZ-41"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-42','WILAYA','Tipaza','42','CENTRE',42,'{"nameAr": "تيبازة", "iso": "DZ-42"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-43','WILAYA','Mila','43','EST',43,'{"nameAr": "ميلة", "iso": "DZ-43"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-44','WILAYA','Aïn Defla','44','CENTRE',44,'{"nameAr": "عين الدفلى", "iso": "DZ-44"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-45','WILAYA','Naâma','45','OUEST',45,'{"nameAr": "النعامة", "iso": "DZ-45"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-46','WILAYA','Aïn Témouchent','46','OUEST',46,'{"nameAr": "عين تيموشنت", "iso": "DZ-46"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-47','WILAYA','Ghardaïa','47','SUD',47,'{"nameAr": "غرداية", "iso": "DZ-47"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-48','WILAYA','Relizane','48','OUEST',48,'{"nameAr": "غليزان", "iso": "DZ-48"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-49','WILAYA','Timimoun','49','SUD',49,'{"nameAr": "تيميمون", "iso": "DZ-49"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-50','WILAYA','Bordj Badji Mokhtar','50','SUD',50,'{"nameAr": "برج باجي مختار", "iso": "DZ-50"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-51','WILAYA','Ouled Djellal','51','EST',51,'{"nameAr": "أولاد جلال", "iso": "DZ-51"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-52','WILAYA','Béni Abbès','52','SUD',52,'{"nameAr": "بني عباس", "iso": "DZ-52"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-53','WILAYA','In Salah','53','SUD',53,'{"nameAr": "عين صالح", "iso": "DZ-53"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-54','WILAYA','In Guezzam','54','SUD',54,'{"nameAr": "عين قزام", "iso": "DZ-54"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-55','WILAYA','Touggourt','55','SUD',55,'{"nameAr": "تقرت", "iso": "DZ-55"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-56','WILAYA','Djanet','56','SUD',56,'{"nameAr": "جانت", "iso": "DZ-56"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-57','WILAYA','El M''Ghair','57','SUD',57,'{"nameAr": "المغير", "iso": "DZ-57"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-58','WILAYA','El Meniaa','58','SUD',58,'{"nameAr": "المنيعة", "iso": "DZ-58"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-59','WILAYA','Aflou','59','OUEST',59,'{"nameAr": "أفلو", "iso": "DZ-59"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-60','WILAYA','El Abiodh Sidi Cheikh','60','OUEST',60,'{"nameAr": "الأبيض سيدي الشيخ", "iso": "DZ-60"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-61','WILAYA','El Aricha','61','OUEST',61,'{"nameAr": "العريشة", "iso": "DZ-61"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-62','WILAYA','El Kantara','62','EST',62,'{"nameAr": "القنطرة", "iso": "DZ-62"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-63','WILAYA','Barika','63','EST',63,'{"nameAr": "بريكة", "iso": "DZ-63"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-64','WILAYA','Bou Saâda','64','CENTRE',64,'{"nameAr": "بوسعادة", "iso": "DZ-64"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-65','WILAYA','Bir El Ater','65','EST',65,'{"nameAr": "بئر العاتر", "iso": "DZ-65"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-66','WILAYA','Ksar El Boukhari','66','CENTRE',66,'{"nameAr": "قصر البخاري", "iso": "DZ-66"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-67','WILAYA','Ksar Chellala','67','OUEST',67,'{"nameAr": "قصر الشلالة", "iso": "DZ-67"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-68','WILAYA','Aïn Oussara','68','CENTRE',68,'{"nameAr": "عين وسارة", "iso": "DZ-68"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('wilaya-69','WILAYA','Messaâd','69','CENTRE',69,'{"nameAr": "مسعد", "iso": "DZ-69"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-flash_sale','DOCUMENT_TYPE','Vente Flash','FLASH_SALE',NULL,1,'{"prismaCode": "FLASH_SALE"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-restock','DOCUMENT_TYPE','Arrivage','RESTOCK',NULL,2,'{"prismaCode": "RESTOCK"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-quota','DOCUMENT_TYPE','Quota','QUOTA',NULL,3,'{"prismaCode": "QUOTA"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-promotion','DOCUMENT_TYPE','Promotion','PROMOTION',NULL,4,'{"prismaCode": "PROMOTION"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-convention','DOCUMENT_TYPE','Convention','CONVENTION',NULL,5,'{"prismaCode": "CONVENTION"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-catalog','DOCUMENT_TYPE','Catalogue','CATALOG',NULL,6,'{"prismaCode": "CATALOG"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-lab_information','DOCUMENT_TYPE','Information laboratoire','LAB_INFORMATION',NULL,7,'{"prismaCode": "LAB_INFORMATION"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-field_information','DOCUMENT_TYPE','Information terrain','FIELD_INFORMATION',NULL,8,'{"prismaCode": "OTHER"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-letter','DOCUMENT_TYPE','Courrier','LETTER',NULL,9,'{"prismaCode": "LETTER"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-email','DOCUMENT_TYPE','E-mail','EMAIL',NULL,10,'{"prismaCode": "EMAIL"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-commercial_proposal','DOCUMENT_TYPE','Proposition commerciale','COMMERCIAL_PROPOSAL',NULL,11,'{"prismaCode": "COMMERCIAL_PROPOSAL"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-pricing','DOCUMENT_TYPE','Tarif','PRICING',NULL,12,'{"prismaCode": "PRICING"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-exceptional_discount','DOCUMENT_TYPE','Remise','EXCEPTIONAL_DISCOUNT',NULL,13,'{"prismaCode": "EXCEPTIONAL_DISCOUNT"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-rebate','DOCUMENT_TYPE','Ristourne','REBATE',NULL,14,'{"prismaCode": "REBATE"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-stockout','DOCUMENT_TYPE','Rupture','STOCKOUT',NULL,15,'{"prismaCode": "STOCKOUT"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-product_launch','DOCUMENT_TYPE','Lancement produit','PRODUCT_LAUNCH',NULL,16,'{"prismaCode": "PRODUCT_LAUNCH"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-commercial_communication','DOCUMENT_TYPE','Communication commerciale','COMMERCIAL_COMMUNICATION',NULL,17,'{"prismaCode": "COMMERCIAL_COMMUNICATION"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP),
('doctype-other','DOCUMENT_TYPE','Autre','OTHER',NULL,18,'{"prismaCode": "OTHER"}'::jsonb,ARRAY[]::TEXT[],CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
