"use client";
import { FormEvent, useEffect, useState } from "react";
import { WILAYAS, REGION_LABELS } from "@/lib/algeria";
import { UserPlus, Search, Users, ShieldCheck, User, MoreVertical, X, Copy, CheckCircle2, AlertCircle, KeyRound, BriefcaseBusiness, UserCheck } from "lucide-react";
type Role="ADMIN"|"DIRECTOR_GENERAL"|"SUPERVISOR"|"DELEGATE";
type Permissions={canImport:boolean;canUseAI:boolean;canExport:boolean;canEditOwn:boolean;canDeleteOwn:boolean};
type UserRow={id:string;name:string;email:string;phone?:string;role:Role;status:"PENDING"|"ACTIVE"|"INACTIVE"|"SUSPENDED"|"REFUSED"|"ARCHIVED"|"DELETED";supervisorId?:string;region?:"EST"|"OUEST"|"CENTRE"|"SUD";wilaya?:string;supervisor?:{id:string;name:string};permissions:Permissions;mustChangePassword:boolean;lastLoginAt?:string;createdAt:string;_count:{documents:number;records:number;delegates:number}};
const labels:Record<Role,string>={ADMIN:"Administrateur",DIRECTOR_GENERAL:"Directeur Général",SUPERVISOR:"Superviseur",DELEGATE:"Délégué"};
const defaults:Permissions={canImport:true,canUseAI:true,canExport:true,canEditOwn:true,canDeleteOwn:false};
const fresh=()=>({name:"",email:"",phone:"",role:"DELEGATE" as Role,supervisorId:"",region:"" as ""|"EST"|"OUEST"|"CENTRE"|"SUD",wilaya:"",temporaryPassword:`Pi!${crypto.randomUUID().slice(0,8)}Aa7`,permissions:{...defaults}});
export function UsersManager({currentUserId}:{currentUserId:string}){
 const[users,setUsers]=useState<UserRow[]>([]);const[search,setSearch]=useState("");const[statusFilter,setStatusFilter]=useState("");const[modal,setModal]=useState(false);const[form,setForm]=useState(fresh);const[edit,setEdit]=useState<UserRow|null>(null);const[tempPassword,setTempPassword]=useState("");const[transferToId,setTransferToId]=useState("");const[error,setError]=useState("");const[toast,setToast]=useState("");const[loading,setLoading]=useState(false);
 const load=()=>fetch("/api/users").then(r=>r.json()).then(d=>setUsers(d.users||[]));useEffect(()=>{load()},[]);
 const supervisors=users.filter(u=>u.role==="SUPERVISOR"&&u.status==="ACTIVE");
 async function create(e:FormEvent){e.preventDefault();setLoading(true);setError("");const r=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,supervisorId:form.role==="DELEGATE"&&form.supervisorId?form.supervisorId:null,region:form.role==="DELEGATE"&&form.region?form.region:null,wilaya:form.role==="DELEGATE"&&form.wilaya?form.wilaya:null})});const d=await r.json();setLoading(false);if(!r.ok)return setError(d.error);setModal(false);setToast(`Compte de ${form.name} créé. Transmettez-lui son mot de passe temporaire.`);setForm(fresh());load();setTimeout(()=>setToast(""),5000)}
 async function saveEdit(){if(!edit)return;setLoading(true);setError("");const r=await fetch(`/api/users/${edit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:edit.name,email:edit.email,phone:edit.phone||null,role:edit.role,status:edit.status,supervisorId:edit.role==="DELEGATE"?edit.supervisorId||null:null,region:edit.role==="DELEGATE"?edit.region||null:null,wilaya:edit.role==="DELEGATE"?edit.wilaya||null:null,permissions:edit.permissions,...(tempPassword?{temporaryPassword:tempPassword}:{})})});const d=await r.json();setLoading(false);if(!r.ok)return setError(d.error);setEdit(null);setToast("Le rôle et les droits ont été mis à jour.");load();setTimeout(()=>setToast(""),3500)}
 async function removeUser(){if(!edit||!confirm("Archiver ce compte ? L’utilisateur ne pourra plus se connecter et toutes ses données seront conservées."))return;const reason=prompt("Motif de l’archivage :")||"Compte archivé par l’administrateur";const r=await fetch(`/api/users/${edit.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({...(transferToId?{transferToId}:{}),reason})});const d=await r.json();if(!r.ok)return setError(d.error);setEdit(null);setToast("Compte archivé. L’historique et les documents sont conservés.");load()}
 const filtered=users.filter(u=>(!statusFilter||u.status===statusFilter)&&`${u.name} ${u.email} ${labels[u.role]}`.toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-head"><div><h2>Utilisateurs, rôles et équipes</h2><p>Attribuez les rôles, rattachez les délégués et contrôlez chaque droit d’accès.</p></div><button className="btn btn-primary" onClick={()=>{setError("");setModal(true)}}><UserPlus size={16}/> Nouvel utilisateur</button></div>
 <div className="user-kpis rbac-kpis"><Kpi icon={<Users size={18}/>} value={users.length} label="Comptes"/><Kpi icon={<CheckCircle2 size={18}/>} value={users.filter(u=>u.status==="ACTIVE").length} label="Actifs"/><Kpi icon={<UserCheck size={18}/>} value={users.filter(u=>u.role==="SUPERVISOR").length} label="Superviseurs"/><Kpi icon={<AlertCircle size={18}/>} value={users.filter(u=>u.status==="PENDING").length} label="En attente"/></div>
 <section className="card"><div className="filters"><div className="search-box"><Search size={17}/><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, e-mail ou rôle…"/></div><select className="select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tous les comptes</option><option value="ACTIVE">Actifs</option><option value="INACTIVE">Désactivés</option><option value="PENDING">En attente</option><option value="SUSPENDED">Suspendus</option><option value="REFUSED">Refusés</option></select><span className="filter-count">{filtered.length} compte{filtered.length>1?"s":""}</span></div>{filtered.length?<div className="table-scroll"><table className="data-table users-table rbac-table"><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Superviseur / équipe</th><th>Statut</th><th>Documents</th><th>Droits</th><th/></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><span className="user-cell"><i className={`user-avatar ${u.role==="ADMIN"?"admin":""}`}>{u.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</i><span><b>{u.name}</b><small>{u.email}{u.phone?` • ${u.phone}`:""}</small></span></span></td><td><span className={`badge ${u.role==="ADMIN"?"badge-gold":u.role==="DIRECTOR_GENERAL"?"badge-blue":u.role==="SUPERVISOR"?"badge-green":"badge-gray"}`}>{u.role==="ADMIN"?<ShieldCheck size={11}/>:u.role==="DIRECTOR_GENERAL"?<BriefcaseBusiness size={11}/>:<User size={11}/>} {labels[u.role]}</span></td><td>{u.role==="DELEGATE"?(u.supervisor?.name||<span className="cell-sub">Non rattaché</span>):u.role==="SUPERVISOR"?<>{u._count.delegates} délégué{u._count.delegates>1?"s":""}</>:"Vision globale"}</td><td><span className={`status-dot ${u.status.toLowerCase()}`}><i/> {{ACTIVE:"Actif",PENDING:"En attente",INACTIVE:"Inactif",SUSPENDED:"Suspendu",REFUSED:"Refusé",ARCHIVED:"Archivé",DELETED:"Supprimé"}[u.status]}</span></td><td>{u._count.documents}<small className="cell-sub">{u._count.records} données</small></td><td><div className="rights-mini"><i className={u.permissions.canImport?"on":""}>I</i><i className={u.permissions.canUseAI?"on":""}>IA</i><i className={u.permissions.canExport?"on":""}>E</i><i className={u.permissions.canDeleteOwn?"on":""}>S</i></div></td><td><button className="icon-btn" disabled={u.id===currentUserId} onClick={()=>{setError("");setTempPassword("");setTransferToId("");setEdit({...u,permissions:{...defaults,...u.permissions}})}}><MoreVertical size={15}/></button></td></tr>)}</tbody></table></div>:<div className="empty-state"><Users size={23}/><h3>Aucun utilisateur trouvé</h3></div>}</section>
 {modal&&<div className="modal-backdrop"><form className="modal" onSubmit={create}><ModalHead title="Créer un compte autorisé" subtitle="Le nouvel utilisateur changera son mot de passe." close={()=>setModal(false)}/><div className="modal-body">{error&&<ErrorBox text={error}/>}<div className="form-grid"><div className="field"><label>Nom complet</label><input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><RoleField value={form.role} onChange={role=>setForm({...form,role})}/><div className="field"><label>Adresse e-mail</label><input className="input" required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Téléphone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+213…"/></div>{form.role==="DELEGATE"&&<><SupervisorField value={form.supervisorId} supervisors={supervisors} onChange={supervisorId=>setForm({...form,supervisorId})}/><GeographicFields region={form.region} wilaya={form.wilaya} onChange={(region,wilaya)=>setForm({...form,region,wilaya})}/></>}<div className="field span-2"><label>Mot de passe temporaire</label><div className="temporary-password"><KeyRound size={15}/><input value={form.temporaryPassword} onChange={e=>setForm({...form,temporaryPassword:e.target.value})}/><button type="button" onClick={()=>navigator.clipboard.writeText(form.temporaryPassword)}><Copy size={14}/></button></div></div><div className="field span-2"><label>Droits complémentaires</label><PermissionsEditor value={form.permissions} onChange={permissions=>setForm({...form,permissions})}/></div></div></div><ModalFoot loading={loading} cancel={()=>setModal(false)} label="Créer et autoriser"/></form></div>}
 {edit&&<div className="modal-backdrop"><div className="modal"><ModalHead title={`Modifier ${edit.name}`} subtitle={edit.email} close={()=>setEdit(null)}/><div className="modal-body">{error&&<ErrorBox text={error}/>}<div className="form-grid"><div className="field"><label>Nom complet</label><input className="input" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></div><RoleField value={edit.role} onChange={role=>setEdit({...edit,role})}/><div className="field"><label>E-mail</label><input className="input" type="email" value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></div><div className="field"><label>Téléphone</label><input className="input" value={edit.phone||""} onChange={e=>setEdit({...edit,phone:e.target.value})}/></div>{edit.role==="DELEGATE"&&<><SupervisorField value={edit.supervisorId||""} supervisors={supervisors} onChange={supervisorId=>setEdit({...edit,supervisorId})}/><GeographicFields region={edit.region||""} wilaya={edit.wilaya||""} onChange={(region,wilaya)=>setEdit({...edit,region:region||undefined,wilaya})}/></>}<div className="field span-2"><label>État du compte</label><select className="select" value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as UserRow["status"]})}><option value="PENDING">En attente</option><option value="ACTIVE">Actif et autorisé</option><option value="INACTIVE">Inactif</option><option value="SUSPENDED">Suspendu</option><option value="REFUSED">Refusé</option><option value="DELETED">Supprimé (historique conservé)</option></select></div><div className="field span-2"><label>Mot de passe temporaire {edit.status==="PENDING"&&"(obligatoire pour autoriser)"}</label><input className="input" type="text" minLength={12} value={tempPassword} onChange={e=>setTempPassword(e.target.value)} placeholder="12 caractères minimum"/></div><div className="field span-2"><label>Transférer les documents à (en cas de suppression)</label><select className="select" value={transferToId} onChange={e=>setTransferToId(e.target.value)}><option value="">Conserver sans transfert</option>{users.filter(u=>u.id!==edit.id&&u.status==="ACTIVE").map(u=><option value={u.id} key={u.id}>{u.name} — {labels[u.role]}</option>)}</select></div><div className="field span-2"><label>Droits complémentaires</label><PermissionsEditor value={edit.permissions} onChange={permissions=>setEdit({...edit,permissions})}/></div></div></div><div className="modal-foot"><button className="btn btn-danger" onClick={removeUser}>Archiver le compte</button><button className="btn btn-secondary" onClick={()=>setEdit(null)}>Annuler</button><button className="btn btn-primary" disabled={loading} onClick={saveEdit}>{loading?"Enregistrement…":"Enregistrer"}</button></div></div></div>}
 {toast&&<div className="toast success"><CheckCircle2 size={18}/><div><strong>Opération réussie</strong><p>{toast}</p></div></div>}</>
}
function Kpi({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="card"><span>{icon}</span><p><strong>{value}</strong><small>{label}</small></p></div>}
function RoleField({value,onChange}:{value:Role;onChange:(r:Role)=>void}){return <div className="field"><label>Rôle</label><select className="select" value={value} onChange={e=>onChange(e.target.value as Role)}><option value="DELEGATE">Délégué</option><option value="SUPERVISOR">Superviseur</option><option value="DIRECTOR_GENERAL">Directeur Général</option><option value="ADMIN">Administrateur</option></select></div>}
function SupervisorField({value,supervisors,onChange}:{value:string;supervisors:UserRow[];onChange:(id:string)=>void}){return <div className="field span-2"><label>Superviseur responsable</label><select className="select" value={value} onChange={e=>onChange(e.target.value)}><option value="">Non rattaché</option>{supervisors.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>}
function GeographicFields({region,wilaya,onChange}:{region:string;wilaya:string;onChange:(region:""|"EST"|"OUEST"|"CENTRE"|"SUD",wilaya:string)=>void}){const choices=region?WILAYAS.filter(w=>w.region===region):WILAYAS;return <><div className="field"><label>Région du délégué</label><select className="select" value={region} onChange={e=>onChange(e.target.value as any,"")}><option value="">Sélectionner…</option>{Object.entries(REGION_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className="field"><label>Wilaya</label><select className="select" value={wilaya} onChange={e=>onChange(region as any,e.target.value)}><option value="">Sélectionner…</option>{choices.map(w=><option value={w.name} key={w.code}>{String(w.code).padStart(2,"0")} — {w.name}</option>)}</select></div></>}
function PermissionsEditor({value,onChange}:{value:Permissions;onChange:(p:Permissions)=>void}){const defs:[keyof Permissions,string,string][]=[["canImport","Importer des documents","Réservé normalement aux délégués et administrateurs"],["canUseAI","Utiliser l’assistant IA","Questions, comparaisons et rapports"],["canExport","Exporter les données","Excel, PDF et Word"],["canEditOwn","Modifier ses documents","Métadonnées des documents possédés"],["canDeleteOwn","Supprimer ses documents","Autorisation sensible pour les délégués"]];return <div className="permission-list">{defs.map(([key,label,desc])=><div className="permission-item" key={key}><span><b>{label}</b><small>{desc}</small></span><button type="button" className={`switch ${value[key]?"on":""}`} onClick={()=>onChange({...value,[key]:!value[key]})}/></div>)}</div>}
function ModalHead({title,subtitle,close}:{title:string;subtitle:string;close:()=>void}){return <div className="modal-head"><div><h3>{title}</h3><p>{subtitle}</p></div><button type="button" className="icon-btn" onClick={close}><X size={17}/></button></div>}
function ModalFoot({loading,cancel,label}:{loading:boolean;cancel:()=>void;label:string}){return <div className="modal-foot"><button type="button" className="btn btn-secondary" onClick={cancel}>Annuler</button><button className="btn btn-primary" disabled={loading}>{loading?"Création…":label}</button></div>}
function ErrorBox({text}:{text:string}){return <div className="form-alert"><AlertCircle size={15}/>{text}</div>}
