import { NextRequest,NextResponse } from "next/server";
import { createHash,randomUUID } from "node:crypto";
import { z } from "zod";
import { requireApiUser } from "@/lib/auth";
import { canImportDocuments } from "@/lib/access";
import { db } from "@/lib/db";
import { assertSameOrigin,audit,badRequest,clientIp,forbidden,unauthorized } from "@/lib/http";
import { putFile } from "@/lib/storage";
import { linkSignal } from "@/lib/signals";
const schema=z.object({wholesaler:z.string().trim().min(1).max(150),entityType:z.enum(["WHOLESALER","LABORATORY","HEALTH_ESTABLISHMENT","PHARMACY","SUPPLIER","COMPETITOR","OTHER"]).default("WHOLESALER"),entityName:z.string().trim().max(200).default(""),laboratory:z.string().trim().max(200).default(""),product:z.string().trim().min(2).max(300),customDocumentType:z.string().trim().max(150).default(""),documentType:z.enum(["FLASH_SALE","RESTOCK","COMMERCIAL_PROPOSAL","QUOTA","PROMOTION","CONVENTION","REBATE","EXCEPTIONAL_DISCOUNT","PRICING","CATALOG","STOCKOUT","PRODUCT_LAUNCH","COMMERCIAL_COMMUNICATION","LAB_INFORMATION","LETTER","EMAIL","OTHER"]),region:z.string().trim().max(150).default(""),wilaya:z.string().trim().max(100).default(""),date:z.string().min(8),description:z.string().trim().min(5).max(5000),source:z.string().trim().min(2).max(300),priority:z.enum(["LOW","NORMAL","HIGH","URGENT"]),confidence:z.coerce.number().int().min(0).max(100),isStrategic:z.enum(["true","false"]).transform(v=>v==="true")});
const offerMap:Record<string,"FLASH_SALE"|"RESTOCK"|"PROMOTION"|"DISCOUNT"|"NEW_PRODUCT"|"OFFER"|"OTHER">={FLASH_SALE:"FLASH_SALE",RESTOCK:"RESTOCK",PROMOTION:"PROMOTION",REBATE:"DISCOUNT",EXCEPTIONAL_DISCOUNT:"DISCOUNT",PRODUCT_LAUNCH:"NEW_PRODUCT",COMMERCIAL_PROPOSAL:"OFFER",QUOTA:"OFFER"};
export async function POST(request:NextRequest){
 if(!assertSameOrigin(request))return forbidden();const user=await requireApiUser();if(!user)return unauthorized();if(!canImportDocuments(user))return forbidden();
 const form=await request.formData().catch(()=>null);if(!form)return badRequest("Formulaire invalide.");const parsed=schema.safeParse(Object.fromEntries([...form.entries()].filter(([,v])=>typeof v==="string")));if(!parsed.success)return badRequest(parsed.error.issues[0]?.message||"Information incomplète.");const base=parsed.data;const wilayaRef=base.wilaya?await db.referenceEntity.findFirst({where:{type:"WILAYA",name:base.wilaya,active:true},select:{region:true}}):null;if(base.wilaya&&!wilayaRef)return badRequest("Sélectionnez une wilaya valide.");const m={...base,region:wilayaRef?.region||base.region};
 const photos=form.getAll("attachments").filter((x):x is File=>x instanceof File&&x.size>0).slice(0,5);const allowed=new Set(["application/pdf","application/zip","application/x-zip-compressed","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel"]);for(const p of photos)if((!p.type.startsWith("image/")&&!allowed.has(p.type))||p.size>8*1024*1024)return badRequest("Chaque pièce jointe doit être une image, PDF, Word, Excel ou ZIP de moins de 8 Mo.");
 const payload=JSON.stringify({...m,submittedBy:user.name,submittedAt:new Date().toISOString()},null,2);const buffer=Buffer.from(payload,"utf8");const storageBase=`${user.id}/${new Date().toISOString().slice(0,10)}/${randomUUID()}`;const mainKey=`${storageBase}-information-terrain.json`;await putFile(mainKey,buffer,"application/json");
 const attachments:{originalName:string;storageKey:string;mimeType:string;size:number}[]=[];for(const photo of photos){const key=`${storageBase}-${randomUUID()}-${photo.name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]/g,"-").slice(-100)}`;await putFile(key,Buffer.from(await photo.arrayBuffer()),photo.type);attachments.push({originalName:photo.name,storageKey:key,mimeType:photo.type,size:photo.size})}
 const date=new Date(`${m.date}T12:00:00Z`);const complete=Boolean(m.wholesaler&&m.product&&m.documentType&&m.region&&m.wilaya&&m.description);const points=[{points:8,reason:"MANUAL_INFORMATION",details:"Information terrain ajoutée"},...(complete?[{points:10,reason:"COMPLETE_INFORMATION",details:"Information complète"}]:[]),...(m.isStrategic?[{points:20,reason:"STRATEGIC_INFORMATION",details:"Information stratégique"}]:[]),...attachments.map(()=>({points:5,reason:"PHOTO_ADDED",details:"Photo ajoutée"}))];
 const document=await db.document.create({data:{userId:user.id,originalName:`Information terrain - ${m.product}.json`,storageKey:mainKey,mimeType:"application/json",size:buffer.length,sha256:createHash("sha256").update(buffer).digest("hex"),status:"COMPLETED",reviewStatus:"PENDING",sourceKind:"MANUAL",fieldSource:m.source,entityType:m.entityType,entityName:m.entityName||m.wholesaler,wilaya:m.wilaya||null,confidenceLevel:m.confidence,isStrategic:m.isStrategic,wholesaler:m.entityType==="WHOLESALER"?(m.entityName||m.wholesaler):m.wholesaler==="Autre"?null:m.wholesaler,documentType:m.documentType,customDocumentType:m.customDocumentType||null,documentDate:date,receivedAt:new Date(),region:m.region||null,laboratory:m.laboratory||null,comments:m.description,priority:m.priority,confidentiality:"INTERNAL",attachments:{create:attachments.map(a=>({...a,uploadedById:user.id}))},records:{create:{userId:user.id,observedAt:date,wholesaler:m.entityType==="WHOLESALER"?(m.entityName||m.wholesaler):m.wholesaler==="Autre"?null:m.wholesaler,laboratory:m.laboratory||null,product:m.product,offerType:offerMap[m.documentType]||"OTHER",wilaya:m.wilaya||null,region:m.region||null,comments:m.description,confidence:m.confidence/100,rawExtraction:{entryMode:"manual",...m}}},scoreEvents:{create:points.map(p=>({...p,userId:user.id}))}},include:{records:true}});
 const createdRecord=document.records[0];if(createdRecord)await linkSignal({recordId:createdRecord.id,documentId:document.id,userId:user.id,wholesaler:createdRecord.wholesaler,laboratory:createdRecord.laboratory,product:createdRecord.product,offerType:createdRecord.offerType,region:m.region,wilaya:m.wilaya});const owner=await db.user.findUnique({where:{id:user.id},select:{supervisorId:true}});const recipients=await db.user.findMany({where:{status:"ACTIVE",OR:[{role:"ADMIN"},...(owner?.supervisorId?[{id:owner.supervisorId}]:[])]},select:{id:true}});if(recipients.length)await db.alert.createMany({data:recipients.map(r=>({userId:r.id,type:"NEW_FIELD_INFORMATION",severity:m.priority==="URGENT"?"CRITICAL":m.priority==="HIGH"?"WARNING":"INFO",title:"Nouvelle information terrain",message:`${m.product} — ${m.wholesaler}`}))});await audit(user.id,"MANUAL_INFORMATION_CREATED","Document",document.id,{product:m.product,wholesaler:m.wholesaler,points:points.reduce((s,p)=>s+p.points,0)},clientIp(request));return NextResponse.json({document,points:points.reduce((s,p)=>s+p.points,0)},{status:201});
}
